<h1 align='center' >Computer Application in Engineering Design Lab</h1>
<h2 align='center' >Mid Term, BCE Fall 2022</h2>
<h3 align='left' >Student Name: Osama Anees Mirza</h3>
<h3 align='left' >Student Roll Number: 210286</h3>
<h3 align='left' >Instructor: Muhammad Farooq Khan</h3>
<h4>Date: 24-Nov-2022</h4>

In [1]:
class1=input("Enter Class#1 Name: ")
class2=input("Enter Class#2 Name: ")
class3=input("Enter Class#3 Name: ")
class4=input("Enter Class#4 Name: ")

Enter Class#1 Name:  a
Enter Class#2 Name:  b
Enter Class#3 Name:  c
Enter Class#4 Name:  d


In [2]:
def menu():
    print("Press 1 for CE-112L MTS 2A")
    print("Press 2 for CE-112L MTS 2B")
    print("Press 3 for CE-112L BEEP 2-A")
    print("Press 4 for CE-115L BEBME 1A")
    print("Press 5 to Exit")

In [3]:
import numpy as np
import pandas as pd
classname="ClassName"
menu()
op=int(input("Select Options: "))
while(op!=5):
    global classname
    if(op==1):
        df = pd.read_csv("/home/baymax/Air Uni Code/Sir-Farooq/Mid/CE-112LBEEP2A.csv")
        # print(df)
        classname="CE-112LBEEP2AResult.csv"
        break
    if(op==2):
        df = pd.read_csv("/home/baymax/Air Uni Code/Sir-Farooq/Mid/CE-112LMTS2B.csv")
        # print(df)
        classname="CE-112LMTS2BResult.csv"
        break
    elif(op==3):
        df = pd.read_csv("/home/baymax/Air Uni Code/Sir-Farooq/Mid/CE-112LBEEP2A.csv")
        # print(df)
        classname="CE-112LBEEP2AResult.csv"
        break
    elif(op==4):
        df = pd.read_csv("/home/baymax/Air Uni Code/Sir-Farooq/Mid/CE-115LBEBME1A.csv")
        # print(df)
        classname="CE-115LBEBME1AResult.csv"
        break
    elif(op==5):
        print("Exiting...")
    else:
        print("Wrong input. Run again")
        menu()
        op=int(input("Select Options: "))

Press 1 for CE-112L MTS 2A
Press 2 for CE-112L MTS 2B
Press 3 for CE-112L BEEP 2-A
Press 4 for CE-115L BEBME 1A
Press 5 to Exit


Select Options:  20


Wrong input. Run again
Press 1 for CE-112L MTS 2A
Press 2 for CE-112L MTS 2B
Press 3 for CE-112L BEEP 2-A
Press 4 for CE-115L BEBME 1A
Press 5 to Exit


Select Options:  20


Wrong input. Run again
Press 1 for CE-112L MTS 2A
Press 2 for CE-112L MTS 2B
Press 3 for CE-112L BEEP 2-A
Press 4 for CE-115L BEBME 1A
Press 5 to Exit


Select Options:  20


Wrong input. Run again
Press 1 for CE-112L MTS 2A
Press 2 for CE-112L MTS 2B
Press 3 for CE-112L BEEP 2-A
Press 4 for CE-115L BEBME 1A
Press 5 to Exit


Select Options:  20


Wrong input. Run again
Press 1 for CE-112L MTS 2A
Press 2 for CE-112L MTS 2B
Press 3 for CE-112L BEEP 2-A
Press 4 for CE-115L BEBME 1A
Press 5 to Exit


Select Options:  20


Wrong input. Run again
Press 1 for CE-112L MTS 2A
Press 2 for CE-112L MTS 2B
Press 3 for CE-112L BEEP 2-A
Press 4 for CE-115L BEBME 1A
Press 5 to Exit


Select Options:  1


In [5]:
w1=w2=w3=w4=w5=0
while(w1+w2+w3+w4+w5!=100 or w1+w2+w3+w4+w5<100):
    w1=int(input("Enter Weightage of Lab Reports:"))
    w2=int(input("Enter Weightage of Lab Performance:"))
    w3=int(input("Enter Weightage of Midterm:"))
    w4=int(input("Enter Weightage of Final term:"))
    w5=int(input("Enter Weightage of CEA:"))
    if(w1+w2+w3+w4+w5!=100):
        print("The Weightages should add up to 100")

Enter Weightage of Lab Reports: 20
Enter Weightage of Lab Performance: 20
Enter Weightage of Midterm: 20
Enter Weightage of Final term: 20
Enter Weightage of CEA: 20


In [6]:
def display():
    print("Press 1 to display class result: ")
    print("Press 2 To generate class result in csv: ")
    print("Press 3 for displaying student info: ")
    print("Press 4 to exit: ")

In [16]:
def CalculateClassResult():
    # Lab Performance
    LabPer=np.array(df.iloc[:,2:16])
    print("Lab Performance:")
    print(LabPer)
    print(LabPer.shape)
    print("ObtainedLabPer:")
    ObtainedLabPer=np.sum(LabPer,axis=1,dtype=float)
    print(ObtainedLabPer)
    print(ObtainedLabPer.shape)
    # (obtained marks/total marks)*weightage
    for i in range (len(ObtainedLabPer)):
        ObtainedLabPer[i]=(ObtainedLabPer[i]/210)*w1
    # print(ObtainedLabPer.reshape(23,1))

    # Lab Report
    LabReport=np.array(df.iloc[:,16:30])
    ObtainedLabReport=np.sum(LabReport,axis=1,dtype=float)
    # (obtained marks/total marks)*weightage
    for i in range (len(ObtainedLabReport)):
        ObtainedLabReport[i]=(ObtainedLabReport[i]/210)*w2
    # print(ObtainedLabReport.reshape(23,1))

    # MidTerm
    Mid=np.array(df.iloc[:,30:31])
    ObtainedMid=np.sum(Mid,axis=1,dtype=float)
    # (obtained marks/total marks)*weightage
    for i in range (len(Mid)):
        ObtainedMid[i]=(ObtainedMid[i]/55)*w3
    # print(ObtainedMid.reshape(23,1))

 
    # Final Term
    Final=np.array(df.iloc[:,31:32])
    ObtainedFinal=np.sum(Final,axis=1,dtype=float)
    for i in range (len(Final)):
        ObtainedFinal[i]=(ObtainedFinal[i]/50)*w4
    # print(ObtainedFinal.reshape(23,1))

    # CEA
    CEA=np.array(df.iloc[:,32:33])
    ObtainedCEA=np.sum(CEA,axis=1,dtype=float)
    # print(ObtainedCEA)

    for i in range (len(CEA)):
        ObtainedCEA[i]=(ObtainedCEA[i]/20)*w5
    # print(ObtainedCEA.reshape(23,1))
    ResultList=[]
    TotalResult=[]
    RandomList=[]
    rollnumber=df[("Roll numbers")]
    NameList=df[("Names")]
    rollnumber=np.array(rollnumber)
    for i in range(len(rollnumber)):
        RandomList.append([rollnumber[i],NameList[i],ObtainedLabPer[i],ObtainedLabReport[i],ObtainedMid[i],ObtainedFinal[i],ObtainedCEA[i]])
    
    df4=pd.DataFrame(RandomList)
    Sum=np.array(df4.iloc[:,2:])
    S=np.sum(Sum,axis=1,dtype=float)

    for i in range (len(rollnumber)):
        ResultList.append([rollnumber[i],NameList[i],ObtainedLabPer[i],ObtainedLabReport[i],ObtainedMid[i],ObtainedFinal[i],ObtainedCEA[i],S[i]])
    
    # Calculating Grades
    for i in range (len(rollnumber)):
        if(ResultList[i][7]>=90):
            ResultList[i].append('A')
        elif(ResultList[i][7]>=80):
            ResultList[i].append('B')
        elif(ResultList[i][7]>=70):
            ResultList[i].append('C')
        elif(ResultList[i][7]>=60):
            ResultList[i].append('D')
        elif(ResultList[i][7]>=50):
            ResultList[i].append('E')
        elif(ResultList[i][7]<=50):
            ResultList[i].append("F")
    return ResultList
ResultList=CalculateClassResult()

Lab Performance:
[[ 7  7 15 15  7  7 15 15 15  2  2 13  1  6]
 [ 7  7 10 10 15 15 15 13  7  5  7 12  1  8]
 [ 7  7 15 15 15 15 11 11  6 11 12  9 15 14]
 [ 7  7  7  7 15 15  9  9 12  3  8  3  3  2]
 [ 7  7 11  4 15 15  3  5 11 11 11  9  7 10]
 [ 7  7 12 12  8  8 11 10  9 15  5  2  7  5]
 [ 7  7  7  0 12 12  1  7  6 10  7  3  6  8]
 [ 7  7 10 10 15 15 15 15  9  7 11 11 11  9]
 [ 7  7  8  8  9  9  7  7  7 11 14  3  5 11]
 [ 7  7  7  7 15 15  9  9  3  0 13  8  6 13]
 [ 7  7  8  8 12  7 12 12  1 15  3 10 15  6]
 [ 7  7 12 12 12 12 15 15  1  6  0 12  9 12]
 [ 7  7 10 10 15 15  7  3  5  1  5 12  6 14]
 [ 7  7 15 15 15 15 15 15  8 10  7  5 12  3]
 [ 7  7 15 15 15 15 13 13 15 10  7 12 10  9]
 [ 7  7 15 15 15 15 15 15  4  9 12 10 14 13]
 [ 7  7  9 11 12 12 11 11 10  5  2  2 11  0]
 [ 7  7  7  7 15 15 14 15  3 10  4  8  2  6]
 [ 7  7 10 10 15 15  7  8 10  9 13  4  4 13]
 [ 7  7 15 15 15 15  6  8  5  9 10  0  3 14]
 [ 7  7 10 10  7  7  8  8  7 12  8  7  3  7]
 [ 7  7 12 12 15 15 14 14  1  2  1  3 

In [8]:
def FindByRollNumber():
    Info="Student Not Found!"
    for i in range(len(ResultList)):
        if(ResultList[i][0])==roll:
            Info=ResultList[i]
            break
    print(Info)

In [9]:
def TotalGrade():
    AllTotalGrades=np.array(df1.iloc[:,2:])
    TotalSum=np.sum(AllTotalGrades,axis=1,dtype=float)
    return TotalSum

In [10]:
display()
import csv
op=int(input("Select Options: "))
while(1):
    global classname
    if(op==1):
        CalculateClassResult()
        file = open('result.csv', 'w', newline ='')
        with file:   
            write = csv.writer(file)
            write.writerows(ResultList)
        df1=pd.DataFrame(ResultList)
        df1.columns=["Roll Number","Names","Lab Performance","Lab Report","Mid Term","Final Term","CEA","Total","Grade"]
        print(df1)
        print("\n")
        display()
        op=int(input("Select Options: "))
    elif(op==2):
        file = open(classname, 'w', newline ='')
        with file:   
            write = csv.writer(file)
            write.writerows(ResultList)
        df1=pd.DataFrame(ResultList)
        df1.columns=["Roll Number","Names","Lab Performance","Lab Report","Mid Term","Final Term","CEA","Total","Grade"]
        print("Saved the result in",classname)
        display()
        op=int(input("Select Options: "))
    elif(op==3):
        roll=int(input("Enter Student Roll Number: "))
        FindByRollNumber()
        print("\n")
        display()
        op=int(input("Select Options: "))
    elif(op==4):
        print("\n")
        print("Exiting.......\n")
        break
    else:
        print("Invalid Option. The Program will run again")
        print("\n")
        display()
        op=int(input("Select Options: "))

Press 1 to display class result: 
Press 2 To generate class result in csv: 
Press 3 for displaying student info: 
Press 4 to exit: 


Select Options:  4




Exiting.......



In [15]:
#A Better Representation of Data
df1

Roll Number                          Names  Lab Performance  Lab Report  \
0        210319           Muhammad Ammar Bajwa        12.095238   14.190476   
1        210323                 Waleed Hussain        12.571429   11.619048   
2        210325                 Shahzaib Malik        15.523810   13.809524   
3        210327         Muhammad Tayyab Saddiq        10.190476   12.095238   
4        210331              Hadia Zainab Raza        12.000000    6.952381   
5        210335  Syeda Imtashal Fatima Jaffari        11.238095   10.190476   
6        210339                 Azlan Muhammad         8.857143    8.952381   
7        210341                 Abdullah Zahid        14.476190   16.190476   
8        210351                 Muammar Rehman        10.761905   13.238095   
9        210355                  Abdullah Khan        11.333333    8.666667   
10       210357                   Usama Khalid        11.714286   15.619048   
11       210359                 Muhammad Kazim        12.571429   14.761905   
12       210363                 Muhammad Talha        11.142857    6.095238   
13       210365                 Muhammad Usman        14.190476   13.809524   
14       210369                Mudassar Zahoor        15.523810   10.476190   
15       210371                   Abdul Baasit        15.809524   11.714286   
16       210373                    Taha Khalid        10.476190   12.190476   
17       210377              Abdullah Zulfiqar        11.428571   12.380952   
18       210379                 Usama Zulfiqar        12.571429   13.523810   
19       210381            Ahmad Mahtab Cheema        12.285714   15.619048   
20       210383                   Adnan Bashir        10.285714   13.904762   
21       211986               Shaoib ul Hassan        11.809524   12.857143   
22       211988              Muhammad Ali Khan        11.523810   12.666667   

     Mid Term  Final Term   CEA      Total Grade  
0   15.454545        15.6   7.0  64.340260     D  
1   12.363636         7.6  15.0  59.154113     E  
2   11.090909        15.2  20.0  75.624242     C  
3    8.181818        12.4  14.0  56.867532     E  
4   10.727273         5.2  16.0  50.879654     E  
5   10.181818        10.0   2.0  43.610390     F  
6    8.363636        17.6  14.0  57.773160     E  
7   12.545455         9.6   3.0  55.812121     E  
8    9.636364        12.4   4.0  50.036364     E  
9    5.272727         5.6  18.0  48.872727     F  
10   8.727273         8.8   7.0  51.860606     E  
11  12.000000        17.6   7.0  63.933333     D  
12   2.909091        18.8  19.0  57.947186     E  
13  10.181818         0.4  13.0  51.581818     E  
14  14.363636        13.6   0.0  53.963636     E  
15  10.909091         7.2  15.0  60.632900     D  
16  11.272727        13.6   4.0  51.539394     E  
17  10.363636        12.8   1.0  47.973160     F  
18  10.363636         9.6   3.0  49.058874     F  
19  12.545455        16.0   4.0  60.450216     D  
20   6.909091         2.4  18.0  51.499567     E  
21  11.272727         9.6  16.0  61.539394     D  
22   4.727273        19.6  19.0  67.517749     D

In [16]:
df

Roll numbers                          Names  Lab Performances (out of 15)  \
0         210319           Muhammad Ammar Bajwa                             7   
1         210323                 Waleed Hussain                             7   
2         210325                 Shahzaib Malik                             7   
3         210327         Muhammad Tayyab Saddiq                             7   
4         210331              Hadia Zainab Raza                             7   
5         210335  Syeda Imtashal Fatima Jaffari                             7   
6         210339                 Azlan Muhammad                             7   
7         210341                 Abdullah Zahid                             7   
8         210351                 Muammar Rehman                             7   
9         210355                  Abdullah Khan                             7   
10        210357                   Usama Khalid                             7   
11        210359                 Muhammad Kazim                             7   
12        210363                 Muhammad Talha                             7   
13        210365                 Muhammad Usman                             7   
14        210369                Mudassar Zahoor                             7   
15        210371                   Abdul Baasit                             7   
16        210373                    Taha Khalid                             7   
17        210377              Abdullah Zulfiqar                             7   
18        210379                 Usama Zulfiqar                             7   
19        210381            Ahmad Mahtab Cheema                             7   
20        210383                   Adnan Bashir                             7   
21        211986               Shaoib ul Hassan                             7   
22        211988              Muhammad Ali Khan                             7   

    Unnamed: 3  Unnamed: 4  Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  \
0            7          15          15           7           7          15   
1            7          10          10          15          15          15   
2            7          15          15          15          15          11   
3            7           7           7          15          15           9   
4            7          11           4          15          15           3   
5            7          12          12           8           8          11   
6            7           7           0          12          12           1   
7            7          10          10          15          15          15   
8            7           8           8           9           9           7   
9            7           7           7          15          15           9   
10           7           8           8          12           7          12   
11           7          12          12          12          12          15   
12           7          10          10          15          15           7   
13           7          15          15          15          15          15   
14           7          15          15          15          15          13   
15           7          15          15          15          15          15   
16           7           9          11          12          12          11   
17           7           7           7          15          15          14   
18           7          10          10          15          15           7   
19           7          15          15          15          15           6   
20           7          10          10           7           7           8   
21           7          12          12          15          15          14   
22           7          12          12          15          15           7   

    Unnamed: 9  ...  Unnamed: 23  Unnamed: 24  Unnamed: 25  Unnamed: 26  \
0           15  ...           12            8            3           14   
1           13  ...           10    